/*
 * $Id: custom_tab.c,v 1.1 1996/07/19 16:46:12 grubba Exp $
 *
 * Tables for the customchip address decoding.
 *
 * $Log$
 *
 */

/*
 * Tables
 */

static S16 (*custom_read_tab[])(U32 reg) = {
  NULL,			/* BLTDDAT */
  NULL,			/* DMACONR */
  NULL,			/* VPOSR */
  custom_read_vhposr,	/* VHPOSR */
  NULL,			/* DSKDATR */
  NULL,			/* JOY0DAT */
  NULL,			/* JOY1DAT */
  NULL,			/* CLXDAT */
  NULL,			/* ADKCONR */
  NULL,			/* POT0DAT */
  NULL,			/* POT1DAT */
  NULL,			/* POTGOR */
  NULL,			/* SERDATR */
  NULL,			/* DSKBYTR */
  NULL,			/* INTENAR */
  NULL,			/* INTREQR */

  NULL,			/* DSKPTH */
  NULL,			/* DSKPTL */
  NULL,			/* DSKLEN */
  NULL,			/* DSKDAT */
  NULL,			/* REFPTR */
  NULL,			/* VPOSW */
  NULL,			/* VHPOSW */
  NULL,			/* COPCON */
  NULL,			/* SERDAT */
  NULL,			/* SERPER */
  NULL,			/* POTGO */
  NULL,			/* JOYTEST */
  NULL,			/* STREQU */
  NULL,			/* STRVBL */
  NULL,			/* STRHOR */
  NULL,			/* STRLONG */

  NULL,			/* BLTCON0 */
  NULL,			/* BLTCON1 */
  NULL,			/* BLTAFWM */
  NULL,			/* BLTALWM */
  NULL,			/* BLTCPTH */
  NULL,			/* BLTCPTL */
  NULL,			/* BLTBPTH */
  NULL,			/* BLTBPTL */
  NULL,			/* BLTAPTH */
  NULL,			/* BLTAPTL */
  NULL,			/* BLTDPTH */
  NULL,			/* BLTDPTL */
  NULL,			/* BLTSIZE */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  
  NULL,			/* BLTCMOD */
  NULL,			/* BLTBMOD */
  NULL,			/* BLTAMOD */
  NULL,			/* BLTDMOD */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* BLTCDAT */
  NULL,			/* BLTBDAT */
  NULL,			/* BLTADAT */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* DSKSYNC */

  NULL,			/* COP1LCH */
  NULL,			/* COP1LCL */
  NULL,			/* COP2LCH */
  NULL,			/* COP2LCL */
  NULL,			/* COPJMP1 */
  NULL,			/* COPJMP2 */
  NULL,			/* COPINS */
  NULL,			/* DIWSTRT */
  NULL,			/* DIWSTOP */
  NULL,			/* DDFSTRT */
  NULL,			/* DDFSTOP */
  NULL,			/* DMACON */
  NULL,			/* CLXCON */
  NULL,			/* INTENA */
  NULL,			/* INTREQ */
  NULL,			/* ADKCON */
  
  NULL,			/* AUD0LCH */
  NULL,			/* AUD0LCL */
  NULL,			/* AUD0LEN */
  NULL,			/* AUD0PER */
  NULL,			/* AUD0VOL */
  NULL,			/* AUD0DAT */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* AUD1LCH */
  NULL,			/* AUD1LCL */
  NULL,			/* AUD1LEN */
  NULL,			/* AUD1PER */
  NULL,			/* AUD1VOL */
  NULL,			/* AUD1DAT */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */

  NULL,			/* AUD2LCH */
  NULL,			/* AUD2LCL */
  NULL,			/* AUD2LEN */
  NULL,			/* AUD2PER */
  NULL,			/* AUD2VOL */
  NULL,			/* AUD2DAT */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* AUD3LCH */
  NULL,			/* AUD3LCL */
  NULL,			/* AUD3LEN */
  NULL,			/* AUD3PER */
  NULL,			/* AUD3VOL */
  NULL,			/* AUD3DAT */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */

  NULL,			/* BPL1PTH */
  NULL,			/* BPL1PTL */
  NULL,			/* BPL2PTH */
  NULL,			/* BPL2PTL */
  NULL,			/* BPL3PTH */
  NULL,			/* BPL3PTL */
  NULL,			/* BPL4PTH */
  NULL,			/* BPL4PTL */
  NULL,			/* BPL5PTH */
  NULL,			/* BPL5PTL */
  NULL,			/* BPL6PTH */
  NULL,			/* BPL6PTL */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */

  NULL,			/* BPLCON0 */
  NULL,			/* BPLCON1 */
  NULL,			/* BPLCON2 */
  NULL,			/* zilch */
  NULL,			/* BPL1MOD */
  NULL,			/* BPL2MOD */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* BPL1DAT */
  NULL,			/* BPL2DAT */
  NULL,			/* BPL3DAT */
  NULL,			/* BPL4DAT */
  NULL,			/* BPL5DAT */
  NULL,			/* BPL6DAT */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */

  NULL,			/* SPR0PTH */
  NULL,			/* SPR0PTL */
  NULL,			/* SPR1PTH */
  NULL,			/* SPR1PTL */
  NULL,			/* SPR2PTH */
  NULL,			/* SPR2PTL */
  NULL,			/* SPR3PTH */
  NULL,			/* SPR3PTL */
  NULL,			/* SPR4PTH */
  NULL,			/* SPR4PTL */
  NULL,			/* SPR5PTH */
  NULL,			/* SPR5PTL */
  NULL,			/* SPR6PTH */
  NULL,			/* SPR6PTL */
  NULL,			/* SPR7PTH */
  NULL,			/* SPR7PTL */

  NULL,			/* SPR0POS */
  NULL,			/* SPR0CTL */
  NULL,			/* SPR0DATA */
  NULL,			/* SPR0DATB */
  NULL,			/* SPR1POS */
  NULL,			/* SPR1CTL */
  NULL,			/* SPR1DATA */
  NULL,			/* SPR1DATB */
  NULL,			/* SPR2POS */
  NULL,			/* SPR2CTL */
  NULL,			/* SPR2DATA */
  NULL,			/* SPR2DATB */
  NULL,			/* SPR3POS */
  NULL,			/* SPR3CTL */
  NULL,			/* SPR3DATA */
  NULL,			/* SPR3DATB */

  NULL,			/* SPR4POS */
  NULL,			/* SPR4CTL */
  NULL,			/* SPR4DATA */
  NULL,			/* SPR4DATB */
  NULL,			/* SPR5POS */
  NULL,			/* SPR5CTL */
  NULL,			/* SPR5DATA */
  NULL,			/* SPR5DATB */
  NULL,			/* SPR6POS */
  NULL,			/* SPR6CTL */
  NULL,			/* SPR6DATA */
  NULL,			/* SPR6DATB */
  NULL,			/* SPR7POS */
  NULL,			/* SPR7CTL */
  NULL,			/* SPR7DATA */
  NULL,			/* SPR7DATB */

  NULL,			/* COLOR0 */
  NULL,			/* COLOR1 */
  NULL,			/* COLOR2 */
  NULL,			/* COLOR3 */
  NULL,			/* COLOR4 */
  NULL,			/* COLOR5 */
  NULL,			/* COLOR6 */
  NULL,			/* COLOR7 */
  NULL,			/* COLOR8 */
  NULL,			/* COLOR9 */
  NULL,			/* COLOR10 */
  NULL,			/* COLOR11 */
  NULL,			/* COLOR12 */
  NULL,			/* COLOR13 */
  NULL,			/* COLOR14 */
  NULL,			/* COLOR15 */

  NULL,			/* COLOR16 */
  NULL,			/* COLOR17 */
  NULL,			/* COLOR18 */
  NULL,			/* COLOR19 */
  NULL,			/* COLOR20 */
  NULL,			/* COLOR21 */
  NULL,			/* COLOR22 */
  NULL,			/* COLOR23 */
  NULL,			/* COLOR24 */
  NULL,			/* COLOR25 */
  NULL,			/* COLOR26 */
  NULL,			/* COLOR27 */
  NULL,			/* COLOR28 */
  NULL,			/* COLOR29 */
  NULL,			/* COLOR30 */
  NULL,			/* COLOR31 */
};

static void (*custom_write_tab[])(U32 reg, U16 val) = {
  NULL,			/* BLTDDAT */
  custom_read_only,	/* DMACONR */
  custom_read_only,	/* VPOSR */
  custom_read_only,	/* VHPOSR */
  custom_read_only,	/* DSKDATR */
  NULL,			/* JOY0DAT */
  NULL,			/* JOY1DAT */
  NULL,			/* CLXDAT */
  custom_read_only,	/* ADKCONR */
  NULL,			/* POT0DAT */
  NULL,			/* POT1DAT */
  NULL,			/* POTGOR */
  custom_read_only,	/* SERDATR */
  custom_read_only,	/* DSKBYTR */
  custom_read_only,	/* INTENAR */
  custom_read_only,	/* INTREQR */

  NULL,			/* DSKPTH */
  NULL,			/* DSKPTL */
  NULL,			/* DSKLEN */
  NULL,			/* DSKDAT */
  NULL,			/* REFPTR */
  NULL,			/* VPOSW */
  NULL,			/* VHPOSW */
  NULL,			/* COPCON */
  NULL,			/* SERDAT */
  NULL,			/* SERPER */
  NULL,			/* POTGO */
  NULL,			/* JOYTEST */
  NULL,			/* STREQU */
  NULL,			/* STRVBL */
  NULL,			/* STRHOR */
  NULL,			/* STRLONG */

  NULL,			/* BLTCON0 */
  NULL,			/* BLTCON1 */
  NULL,			/* BLTAFWM */
  NULL,			/* BLTALWM */
  NULL,			/* BLTCPTH */
  NULL,			/* BLTCPTL */
  NULL,			/* BLTBPTH */
  NULL,			/* BLTBPTL */
  NULL,			/* BLTAPTH */
  NULL,			/* BLTAPTL */
  NULL,			/* BLTDPTH */
  NULL,			/* BLTDPTL */
  NULL,			/* BLTSIZE */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  
  NULL,			/* BLTCMOD */
  NULL,			/* BLTBMOD */
  NULL,			/* BLTAMOD */
  NULL,			/* BLTDMOD */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* BLTCDAT */
  NULL,			/* BLTBDAT */
  NULL,			/* BLTADAT */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* DSKSYNC */

  NULL,			/* COP1LCH */
  NULL,			/* COP1LCL */
  NULL,			/* COP2LCH */
  NULL,			/* COP2LCL */
  NULL,			/* COPJMP1 */
  NULL,			/* COPJMP2 */
  NULL,			/* COPINS */
  NULL,			/* DIWSTRT */
  NULL,			/* DIWSTOP */
  NULL,			/* DDFSTRT */
  NULL,			/* DDFSTOP */
  NULL,			/* DMACON */
  NULL,			/* CLXCON */
  custom_write_intena,	/* INTENA */
  custom_write_intreq,	/* INTREQ */
  NULL,			/* ADKCON */
  
  NULL,			/* AUD0LCH */
  NULL,			/* AUD0LCL */
  NULL,			/* AUD0LEN */
  NULL,			/* AUD0PER */
  NULL,			/* AUD0VOL */
  NULL,			/* AUD0DAT */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* AUD1LCH */
  NULL,			/* AUD1LCL */
  NULL,			/* AUD1LEN */
  NULL,			/* AUD1PER */
  NULL,			/* AUD1VOL */
  NULL,			/* AUD1DAT */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */

  NULL,			/* AUD2LCH */
  NULL,			/* AUD2LCL */
  NULL,			/* AUD2LEN */
  NULL,			/* AUD2PER */
  NULL,			/* AUD2VOL */
  NULL,			/* AUD2DAT */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* AUD3LCH */
  NULL,			/* AUD3LCL */
  NULL,			/* AUD3LEN */
  NULL,			/* AUD3PER */
  NULL,			/* AUD3VOL */
  NULL,			/* AUD3DAT */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */

  NULL,			/* BPL1PTH */
  NULL,			/* BPL1PTL */
  NULL,			/* BPL2PTH */
  NULL,			/* BPL2PTL */
  NULL,			/* BPL3PTH */
  NULL,			/* BPL3PTL */
  NULL,			/* BPL4PTH */
  NULL,			/* BPL4PTL */
  NULL,			/* BPL5PTH */
  NULL,			/* BPL5PTL */
  NULL,			/* BPL6PTH */
  NULL,			/* BPL6PTL */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */

  NULL,			/* BPLCON0 */
  NULL,			/* BPLCON1 */
  NULL,			/* BPLCON2 */
  NULL,			/* zilch */
  NULL,			/* BPL1MOD */
  NULL,			/* BPL2MOD */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */
  NULL,			/* BPL1DAT */
  NULL,			/* BPL2DAT */
  NULL,			/* BPL3DAT */
  NULL,			/* BPL4DAT */
  NULL,			/* BPL5DAT */
  NULL,			/* BPL6DAT */
  NULL,			/* UNUSED */
  NULL,			/* UNUSED */

  NULL,			/* SPR0PTH */
  NULL,			/* SPR0PTL */
  NULL,			/* SPR1PTH */
  NULL,			/* SPR1PTL */
  NULL,			/* SPR2PTH */
  NULL,			/* SPR2PTL */
  NULL,			/* SPR3PTH */
  NULL,			/* SPR3PTL */
  NULL,			/* SPR4PTH */
  NULL,			/* SPR4PTL */
  NULL,			/* SPR5PTH */
  NULL,			/* SPR5PTL */
  NULL,			/* SPR6PTH */
  NULL,			/* SPR6PTL */
  NULL,			/* SPR7PTH */
  NULL,			/* SPR7PTL */

  NULL,			/* SPR0POS */
  NULL,			/* SPR0CTL */
  NULL,			/* SPR0DATA */
  NULL,			/* SPR0DATB */
  NULL,			/* SPR1POS */
  NULL,			/* SPR1CTL */
  NULL,			/* SPR1DATA */
  NULL,			/* SPR1DATB */
  NULL,			/* SPR2POS */
  NULL,			/* SPR2CTL */
  NULL,			/* SPR2DATA */
  NULL,			/* SPR2DATB */
  NULL,			/* SPR3POS */
  NULL,			/* SPR3CTL */
  NULL,			/* SPR3DATA */
  NULL,			/* SPR3DATB */

  NULL,			/* SPR4POS */
  NULL,			/* SPR4CTL */
  NULL,			/* SPR4DATA */
  NULL,			/* SPR4DATB */
  NULL,			/* SPR5POS */
  NULL,			/* SPR5CTL */
  NULL,			/* SPR5DATA */
  NULL,			/* SPR5DATB */
  NULL,			/* SPR6POS */
  NULL,			/* SPR6CTL */
  NULL,			/* SPR6DATA */
  NULL,			/* SPR6DATB */
  NULL,			/* SPR7POS */
  NULL,			/* SPR7CTL */
  NULL,			/* SPR7DATA */
  NULL,			/* SPR7DATB */

  NULL,			/* COLOR0 */
  NULL,			/* COLOR1 */
  NULL,			/* COLOR2 */
  NULL,			/* COLOR3 */
  NULL,			/* COLOR4 */
  NULL,			/* COLOR5 */
  NULL,			/* COLOR6 */
  NULL,			/* COLOR7 */
  NULL,			/* COLOR8 */
  NULL,			/* COLOR9 */
  NULL,			/* COLOR10 */
  NULL,			/* COLOR11 */
  NULL,			/* COLOR12 */
  NULL,			/* COLOR13 */
  NULL,			/* COLOR14 */
  NULL,			/* COLOR15 */

  NULL,			/* COLOR16 */
  NULL,			/* COLOR17 */
  NULL,			/* COLOR18 */
  NULL,			/* COLOR19 */
  NULL,			/* COLOR20 */
  NULL,			/* COLOR21 */
  NULL,			/* COLOR22 */
  NULL,			/* COLOR23 */
  NULL,			/* COLOR24 */
  NULL,			/* COLOR25 */
  NULL,			/* COLOR26 */
  NULL,			/* COLOR27 */
  NULL,			/* COLOR28 */
  NULL,			/* COLOR29 */
  NULL,			/* COLOR30 */
  NULL,			/* COLOR31 */
};
